serverAddr = "" # frps服务器地址
serverPort = 7000 # 服务器端口
auth.method = "token"
auth.token = "" # token

[[proxies]]
name = "test"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8000
remotePort = 9000